drop table if exists Cart CASCADE;
drop table if exists Product CASCADE; 
drop table if exists USERS CASCADE; 

create table Cart (
   cart_id bigint generated by default as identity,
    user_id bigint,
    primary key (cart_id)
);

create table Product (
   product_id bigint generated by default as identity,
    age integer not null,
    agency varchar(255),
    amount bigint not null,
    cartCount bigint,
    interestRate bigint not null,
    job varchar(255),
    name varchar(255),
    repayPeriod bigint not null,
    cart_id bigint,
    primary key (product_id)
);

create table USERS (
   user_Id bigint generated by default as identity,
    createdDate timestamp,
    modifiedDate timestamp,
    age integer not null,
    job varchar(255),
    name varchar(255),
    password varchar(255),
    username varchar(255),
    cart_id bigint,
    primary key (user_Id)
);

alter table Cart 
   add constraint FKqhu6xtuquahvnebwgqat2hfqa 
   foreign key (user_id) 
   references USERS;

alter table Product 
   add constraint FKdoypnklcfpi3kbpfw845e9of4 
   foreign key (cart_id) 
   references Cart;
   
alter table USERS 
   add constraint FKq4iff8ul3mx5xybcr10dtqooa 
   foreign key (cart_id) 
   references Cart;
   
INSERT INTO USERS (age, job, name, password, username) 
VALUES(12, 'STUDENT', 'testname', '$2a$12$2PAOtUoIWx48Rz.QnRwMsOfhuDYJ6HO2FwlDOngN1tHuvQG4vg0Ae
', 'test');

INSERT INTO PRODUCT (agency, amount, interestRate, job, name, repayPeriod, age)
VALUES('FAST은행',2000000,1.5,'프리랜서','프리랜서를 위한 대출',150, 30);


